Correct minor glitches. Make sure pdf files in required/* are built.

diff --git a/Construct b/Construct
--- a/Construct
+++ b/Construct
@@ -42,9 +42,22 @@ $LDOCS = [ qw(
        usrguide
 )];
 
-@docfiles = map { "doc/$_.pdf" } @$LDOCS;
 
-Export qw ( CONS DISTRIB BUILD FORMAT FORMATPDF LDOCS );
+@toolspdffiles = map { my $x=$_; $x =~ s/\.dtx$/.pdf/; $x; } <required/tools/*.dtx>;
+@babelpdffiles = ();
+@cyrillicpdffiles = ();
+@graphicspdffiles = qw(required/graphics/grfguide.pdf);
+
+@docfiles = (
+	@toolspdffiles,
+	@babelpdffiles,
+	@cyrillicpdffiles,
+	@graphicspdffiles,
+	map { "doc/$_.pdf" } @$LDOCS,
+);
+
+
+Export qw ( CONS DISTRIB BUILD FORMAT FORMATPDF LDOCS);
 
 # A standard construction environment.
 $CONS = new cons(
@@ -57,8 +70,7 @@ sub cons::CompileTeX {
     $ext = "tex" unless defined $ext;
     foreach my $tgt (@$nms) {
 	$cons->Command(["$dir/$tgt.pdf"], ($FORMATPDF,"#$BUILD/$tgt.$ext"),qq(
-	    export TEXINPUTS=../%2:d:\$TEXINPUTS ; %RUNTEX %1:a %2:a || echo NOT GOOD
-            mv build/%>:f %>:a
+	    export TEXINPUTS=../%2:d:\$TEXINPUTS ; %RUNTEX %1:a %2:a && mv %>:f %>:a || echo NOT GOOD
         ));
     }
 }
@@ -123,7 +135,7 @@ Command $CONS ["$FORMAT"], (@supportfiles,"unpacked/unpack.log"), qq(
 	( cd build ; yes | TEXINPUTS=.:../unpacked etex -ini -etex latex.ltx)
 );
 Command $CONS ["$FORMATPDF"], (@supportfiles,"unpacked/unpack.log"), qq(
-        ln -f -s latex.ltx pdflatex.ltx
+        ln -f -s latex.ltx build/pdflatex.ltx
 	(cd build ; yes | TEXINPUTS=.:../unpacked pdfetex -ini -jobname=pdflatex "*pdflatex.ini" latex.ltx)
 );
 
@@ -133,7 +145,7 @@ Build (
 );
 
 # zip to distribution files
-Command $CONS ["latex2e-distrib.zip"], ("unpacked/unpack.log",@docfiles), qq(
+Command $CONS ["latex2e-distrib.zip"], ("unpacked/unpack.log",@docfiles,@requireddocs), qq(
 	zip -y -r latex2e-distrib.zip base unpacked doc required -x base/changes.old.txt -x unpacked/changes.old.txt -x unpacked/unpack.log -x Construct -x \\*/.consign -x \\*/Conscript -x \\*/.svn/ -x \\*/.svn/\\* -x \\*.aux -x \\*.dvi -x \\*.glo -x \\*.idx -x \\*.log
 );
 
@@ -142,5 +154,6 @@ Build ( "testfiles/Conscript" );
 Build qw(
       required/tools/Conscript
       required/cyrillic/Conscript
+      required/graphics/Conscript
 );
 
